### ISSUE TITLE
back-end

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#1]
Kuya, mag pabuhat na niya ko sa back-end sa atong output ang information sa tax and such kay naa ra ari.

- tax (3%)
- ang purpose sa total sa table kay ang total pricing depende sa quantity
- ang grand total is ang whole total amount dala sa tax.

I think na yabag na sad ko ni ang sizing sa may sidebar, i hope wala ra. If naa kay need ipa clarify nako chat lng. Thank you

**Comment by rondinabrybry** [comment]
Cgi2 tnxxx. Update ra nya kos gc

**Comment by rondinabrybry** [comment]
DONE
