### ISSUE TITLE
add product (front-end)

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#2]
ari nga part is basically mura tag mag buhat ug crud. Mag buhat ta ug list sa mga producsts nato.

![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/107679280/bf875b52-0264-464c-8d63-99437b73689f)

somewhat ingani ang atong design but ang naka butang sa table is:

- [ ] product name
- [ ] product price 

buttons:
- [ ] edit
- [ ] delete 
- [ ] not available

lastly naa ni add button para maka add tag laing product and then 

- [ ] seach bar para maka search ta sa mga products

**Comment by ziblue** [comment]
![Uploading 20231115_184434_0000.png…]()
