### ISSUE TITLE
login (front-end)

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#3]
mag buhat mo ug login page, similar ra sa uban nato nga na buhat nga login so far but di ta mag buhat ug register page lng. kay naa koy lain plano ana.

features: 

- [x] username
- [x] password

**Comment by kem07** [comment]
![final](https://github.com/massachusetts-of-ctu/maricakes/assets/146392648/e67dd7b3-2d4d-4b30-ab65-ddc9c3b20c81)
