### ISSUE TITLE
dashboard/analytics (front-end)

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#5]
ari sa dashboard, atong i butang ari nga part is pila atong total sales karon, and pila atong number of transactions nga na buhat para karon nga day. Ug mag add sad ta ug pila atong sales for the month.

- [ ] total of sales today
- [ ] total of transactions today
- [ ] total number of sales for the month

Similar concept ani but mag follow ta kung unsay atong i require
![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/107679280/6d3730a4-1332-4ada-9956-2a86f45da219)

**Comment by kem07** [comment]
![final](https://github.com/massachusetts-of-ctu/maricakes/assets/146392648/34c150c1-bfcd-42be-af32-5ad43b7b36e5)
