### ISSUE TITLE
customer/order log (html)

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#6]
magpa buhat kog order log, diha naka butang ang lista sa mga customers nga ni order:

![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/107679280/c0cd41b5-0e0f-441f-9a5d-535b0fea4505)

ang kanang naa sa babaw nga mga square kay mao na ang analytics such as:

 

- [ ] total of sales today
- [ ] total of transactions today 
- [ ] total number of sales for the month 

then sulod sa details button kay kani

![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/107679280/f8999ec3-f615-4fbd-b784-5f6ae1b6f781)

ang sa sidebar sa left side kay ipa-dako lng kay ara nato i butang ang navigation

**Comment by ziblue** [comment]
![20231114_112010_0002.jpg](https://github.com/massachusetts-of-ctu/maricakes/assets/147050454/67f3cb5a-b53e-4dfe-b489-9fc73d2a0bf8)

![20231115_183133_0000.png](https://github.com/massachusetts-of-ctu/maricakes/assets/147050454/ba98cc83-7511-4906-a205-06ba7daf19ed)

**Comment by makRobol** [comment]
![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/146397909/b9c9ab49-0491-49f5-8987-9f11f07b7a0d)



![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/146397909/c0c4e99e-7ec5-4c97-b5a7-080dc896e152)
