### ISSUE TITLE
login (html)

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#7]
same ra ni sa kang sir glennard nga layout, ang i adjust lng is ang size ug ang color sa font ug background 

![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/107679280/9445fb11-d4ba-4532-85f2-4c1ca0dd8b3a)

**Comment by makRobol** [comment]
![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/146397909/0a9b1c2d-2afd-4c1c-8894-faab1383faf0)
