### ISSUE TITLE
add product (html)

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/maricakes#8]
ari i butang ang tables sa atong mga products ang sa view details ug sa delete button kay buhati niya ug borders. if mag lisod kag buhat sa search bar, kopyaha lng to ang search bar sa POS.php nga file para ma uniform. Ang color sa header kay dapat uniform sad para di mag ilis-ilis

![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/107679280/f14d2440-3ff9-43f4-b07e-1d6a544b0c47)

**Comment by makRobol** [comment]
![Image](https://github.com/massachusetts-of-ctu/maricakes/assets/146397909/68801cc0-ae39-447d-b14d-21d6fe8cdb57)
